/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20ClubSol from "./ERC20Club.sol";
export type { erc20ClubSol };
export type { MyToken } from "./MyToken";
